name: yapima
dependencies:
  - bioconductor-biomart=2.38.0
  - bioconductor-complexheatmap=1.20.0
  - bioconductor-copyneutralima=1.0.0
  - bioconductor-dmrcate=1.18.0
  - bioconductor-genomicranges=1.34.0
  - bioconductor-limma=3.38.3
  - bioconductor-minfi=1.28.0 # requires manual update to 1.28.4
  - bioconductor-missmethyl=1.16.0
  - pandoc=2.7.2
  - r-base=3.5.1
  - r-circlize=0.4.6
  - r-cluster=2.0.9
  - r-fpc=2.1_11.1 # requires manual update to 2.2.-1
  - r-ggplot2=3.1.1 
  - r-git2r=0.25.2 
  - r-gridextra=2.3 
  - r-gridgraphics=0.3_0 # requires manual update to 0.4-1
  - r-knitr=1.22 # requires manual update to 1.23
