#!/bin/bash

source $CONFIG_FILE
#set -x

export NCORES
export PIPELINE_DIR
export OUTDIR
export RUN_BATCH_CORRECTION
export RUN_SURROGATE_CORRECTION
export RUN_QC
export RUN_PROBE_SELECTION
export RUN_DIFFERENTIAL_METHYLATION
export IDAT_DIR
export SAMPLE_ANNOTATION
export BLACKLIST
export BACKGROUND_CORRECTION
export NORMALIZATION
export REMOVE_EUROPEAN_SNPS
export BATCH_VARS
export VARIANCE_PROPORTION
export SEED

$RSCRIPT_BIN $PIPELINE_DIR/run_process450k.R $BASH2R
